name: Daily fetch measurements

on:
  schedule:
    - cron: '59 20 * * *'  # This cron expression schedules the workflow to run every day at 12:00 UTC
  push:
      branches:
        - master  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Specify the Python version you need
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        #rm *.csv
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        #pip install numpy pandas requests
        
    - name: Run Python script
      run: |
        python get_and_upload_wind_data_sangiuliano.py  

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *.csv  # Replace with the path to your generated CSV file
        git commit -m "Update generated measured CSV file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
